openapi: 3.2.0
info:
  title: external/user_settings/user_settings.proto User Settings…
  version: version not set
tags:
- name: UserSettingsService
paths:
  /api/v0/user-settings/{user.name}/{user.connector}:
    get:
      summary: GetUserSettings returns all of the preferences for a given user
      operationId: UserSettingsService_GetUserSettings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chef.automate.api.user_settings.GetUserSettingsResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      parameters:
      - name: user.name
        in: path
        required: true
        schema:
          type: string
      - name: user.connector
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserSettingsService
    delete:
      summary: DeleteUserSettings deletes all settings for a given user
      operationId: UserSettingsService_DeleteUserSettings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      parameters:
      - name: user.name
        in: path
        required: true
        schema:
          type: string
      - name: user.connector
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserSettingsService
    put:
      summary: PutUserSettings upserts all of the preferences for a given user
      operationId: UserSettingsService_PutUserSettings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chef.automate.api.user_settings.PutUserSettingsResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/grpc.gateway.runtime.Error'
      parameters:
      - name: user.name
        in: path
        required: true
        schema:
          type: string
      - name: user.connector
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserSettingsService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/chef.automate.api.user_settings.PutUserSettingsRequest'
        required: true
components:
  schemas:
    google.protobuf.Any:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
    chef.automate.api.user_settings.GetUserSettingsResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/chef.automate.api.user_settings.User'
        settings:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/chef.automate.api.user_settings.UserSettingValue'
    chef.automate.api.user_settings.PutUserSettingsResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/chef.automate.api.user_settings.User'
    grpc.gateway.runtime.Error:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
    chef.automate.api.user_settings.PutUserSettingsRequest:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/chef.automate.api.user_settings.User'
          description: ID of the user. Cannot be changed. Used to sign in.
        settings:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/chef.automate.api.user_settings.UserSettingValue'
          description: The user settings to persist.
    chef.automate.api.user_settings.UserSettingValue:
      type: object
      properties:
        default_value:
          type: string
          description: Default value for this setting.
        value:
          type: string
          description: Value for this setting.
        enabled:
          type: boolean
          title: Enabled
        valid_values:
          type: array
          items:
            type: string
          description: Valid values for this setting.
    chef.automate.api.user_settings.User:
      type: object
      properties:
        name:
          type: string
        connector:
          type: string
